name: irongrid_app
description: IronGrid App

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
